# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poke',
            name='user_poked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='logreg.User'),
        ),
    ]
